---
- name: Déploiement du VNF Web Server
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Vérifier si le conteneur existe déjà
      shell: docker ps -a -q -f name=vnf-web
      register: web_exists
      ignore_errors: true
      changed_when: false

    - name: Supprimer l'ancien conteneur si existe
      shell: docker rm -f vnf-web
      when: web_exists.stdout != ""
      ignore_errors: true

    - name: Lancer le conteneur Web Server
      shell: docker run -d --name vnf-web -p 8081:80 nginx
      register: web_output

    - name: Afficher le résultat
      debug:
        msg: "Web Server déployé: {{ web_output.stdout }}"